version: "3.7"

services:
  app:
    image: application-api
    ports:
      - "8085:8080"
    depends_on:
      - mysql_db_0
    environment:
      spring.datasource.url: "jdbc:mysql://mysql_db_0:3306/application?useUnicode=true&characterEncoding=utf-8"
  mysql_db_0:
    image: mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678x@X
      MYSQL_DATABASE: application
    ports:
        - "3307:3306"