ALTER TABLE `USERS`
    ADD COLUMN `CREATED_BY`  varchar(50) AFTER `UPDATED_TIME`,
    ADD COLUMN `UPDATED_BY` varchar(50) AFTER `CREATED_BY`;

ALTER TABLE `ROLES`
    ADD COLUMN `CREATED_BY`  varchar(50) AFTER `UPDATED_TIME`,
    ADD COLUMN `UPDATED_BY` varchar(50) AFTER `CREATED_BY`;

ALTER TABLE `PERMISSIONS`
    ADD COLUMN `CREATED_BY`  varchar(50) AFTER `UPDATED_TIME`,
    ADD COLUMN `UPDATED_BY` varchar(50) AFTER `CREATED_BY`;

ALTER TABLE `USERS_ROLES`
    ADD COLUMN `CREATED_BY`  varchar(50) AFTER `UPDATED_TIME`,
    ADD COLUMN `UPDATED_BY` varchar(50) AFTER `CREATED_BY`;

ALTER TABLE `ROLE_PERMISSIONS`
    ADD COLUMN `CREATED_BY`  varchar(50) AFTER `UPDATED_TIME`,
    ADD COLUMN `UPDATED_BY` varchar(50) AFTER `CREATED_BY`




